<template>
  <vue3dLoader
    filePath="/vue-3d-loader/examples-demo/models/gltf/DamagedHelmet.gltf"
    backgroundColor="rgb(216,217,219)"
    :height="600"
    :width="600"
    outputEncoding="sRGB"
  />
</template>